[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cloudinary>=1.44.2",
    "email-validator>=2.3.0",
    "fastapi>=0.136.1",
    "gitpython>=3.1.50",
    "google-generativeai>=0.8.6",
    "langchain>=0.3.27",
    "langchain-core>=0.3.74",
    "langchain-google-genai>=2.1.10",
    "langchain-text-splitters>=0.3.11",
    "PyGithub>=1.59.1",
    "requests>=2.31.0",
    "motor>=3.7.1",
    "passlib[bcrypt]>=1.7.4",
    "pydantic-settings>=2.14.0",
    "pymongo>=4.17.0",
    "python-dotenv>=1.2.2",
    "python-jose>=3.5.0",
    "python-multipart>=0.0.27",
    "uvicorn>=0.46.0",
]
